services:
  github-runner-ubuntu-jammy:
    image: ghcr.io/rafal-lukawski/github-runner:ubuntu-jammy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS_VERSION: ubuntu-jammy
      platforms:
        - linux/amd64
        # - linux/arm64
  github-runner-ubuntu-noble:
    image: ghcr.io/rafal-lukawski/github-runner:ubuntu-noble
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS_VERSION: ubuntu-noble
      platforms:
        - linux/amd64
        # - linux/arm64

  github-runner-debian-bookworm:
    image: ghcr.io/rafal-lukawski/github-runner:debian-bookworm
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS_VERSION: debian-bookworm
      platforms:
        - linux/amd64
        # - linux/arm64

  github-runner-debian-trixie:
    image: ghcr.io/rafal-lukawski/github-runner:debian-trixie
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS_VERSION: debian-trixie
      platforms:
        - linux/amd64
        # - linux/arm64
